### ISSUE TITLE
Which class is responsible for generating access token?

### ISSUE THREAD

**Issue by Devesh145** [handioq/Diber-backend#37]
I am new to this project so please help me to identify the class which is responsible for generating the access token.

**Comment by atereshkov** [comment]
Hey, @Devesh145. I use Spring Security with OAuth2. U can find [more information here.](https://github.com/atereshkov/spring-boot-security-oauth2)

**Comment by Devesh145** [comment]
hi.. @atereshkov  Thanks for your reply but I want to know the class name from the project which is generating the token. I am unaware about token generation process in this project so want to start from the step of token generation.Please help me with the same.

**Comment by atereshkov** [comment]
@Devesh145 If I got you right, take a look at [AuthorizationServerConfiguration.java](https://github.com/atereshkov/Diber-backend/blob/master/src/main/java/com/github/handioq/diber/configuration/security/AuthorizationServerConfiguration.java) and DefaultTokenServices.

I'm using Spring Security based token authorization so remaining customization (tokens, etc) is up to you.

**Comment by Devesh145** [comment]
@atereshkov Okay thanks
